name: "Build Garden esp app"
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.8.1'
      - run: flutter pub get

      - name: Test application
        run: flutter test

      - name: Build dev apk
        run: flutter build apk
      # Build iOS versionss
      # - run: flutter build ios --release --no-codesign

      # Upload generated apk to the artifacts.
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk